/**
 * Contains parameters from configuration file.
 * */
public enum Parameter {
	POPULATION_SIZE,
	MUTATION_PROBABILITY,
	TOTAL_NUMBER_OF_ITERATIONS,	
	DIMENSIONALITY,
	R_LOWER_BOUND,
	R_UPPER_BOUND,
	T_LOWER_BOUND,
	T_UPPER_BOUND,
	R_STANDARD_DEV,
	T_STANDARD_DEV
}
